[package]

authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "termios"
version = "0.0.0"

[build-dependencies.bindgen]
branch = "free-lifetime"
git = "https://github.com/japaric/rust-bindgen"
